id: I09D98003
legacy_id: P000382
ocr_import_info:
  bdrc_scan_id: W8464
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T13:10:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:19:15.632863+00:00'
last_modified: 2022-09-04 11:19:24.177935
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8464
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8464
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག་གི་རྒྱུད་བླ་མའི་འགྲེལ་པ།
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics:
  ocr_word_mean_confidence_index: 0.7066110219298438
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG12615:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12615
      total_pages: 202
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12615.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.7066110219298438
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
